# Generated by Django 5.2.5 on 2025-08-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_service_service_name_en_service_service_name_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property',
            new_name='property_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel_app.property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_app.property'),
        ),
    ]
